changes

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -65,34 +65,35 @@ jobs:
       - name: Deploy to GKE (Rolling Deployment)
         run: |
           kubectl apply -n $NAMESPACE -f deployment.yaml
-          kubectl rollout status -n $NAMESPACE deployment "$DEPLOYMENT_NAME"
+          kubectl rollout restart -n $NAMESPACE deployment "$DEPLOYMENT_NAME"
+          kubectl get services -o wide
 
-      - name: Post-Deployment Integration Tests
-        run: |
-          echo "Running Integration Tests..."
-          # Replace this with your actual integration test script/command
-          curl --fail http://34.49.50.0:8080/api/data-aggregator-service/health || exit 1
+#      - name: Post-Deployment Integration Tests
+#        run: |
+#          echo "Running Integration Tests..."
+#          # Replace this with your actual integration test script/command
+#          curl --fail http://34.49.50.0:8080/api/data-aggregator-service/health || exit 1
 
       - name: Verify Deployment
         run: kubectl get services -n $NAMESPACE -o wide
 
-  periodic-integration-tests:
-    name: Periodic Integration Tests
-    runs-on: ubuntu-latest
-    steps:
-      - name: Setup Google Cloud CLI
-        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
-        env:
-          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
-        with:
-          service_account_key: ${{ secrets.GKE_SERVICE_ACCOUNT_KEY }}
-          project_id: ${{ secrets.GKE_PROJECT_ID }}
-
-      - name: Get Cluster Credentials
-        run: gcloud container clusters get-credentials "$SI_CLUSTER" --zone "$SI_ZONE" --project "$PROJECT_ID"
-
-      - name: Run Integration Tests
-        run: |
-          echo "Running Scheduled Integration Tests..."
-          # Replace this with your actual integration test script/command
-          curl --fail http://34.49.50.0:8080/api/data-aggregator-service/health || exit 1
+#  periodic-integration-tests:
+#    name: Periodic Integration Tests
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Setup Google Cloud CLI
+#        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
+#        env:
+#          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
+#        with:
+#          service_account_key: ${{ secrets.GKE_SERVICE_ACCOUNT_KEY }}
+#          project_id: ${{ secrets.GKE_PROJECT_ID }}
+#
+#      - name: Get Cluster Credentials
+#        run: gcloud container clusters get-credentials "$SI_CLUSTER" --zone "$SI_ZONE" --project "$PROJECT_ID"
+#
+#      - name: Run Integration Tests
+#        run: |
+#          echo "Running Scheduled Integration Tests..."
+#          # Replace this with your actual integration test script/command
+#          curl --fail http://34.49.50.0:8080/api/data-aggregator-service/health || exit 1
